-- This script creates tables and upserts data.
-- It's designed to be safely run multiple times.

-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    venue_name TEXT NOT NULL,
    venue_address TEXT NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    phone_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS performers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Upsert the main event details, ensuring it has a stable ID of 1.
INSERT INTO events (id, name, description, venue_name, venue_address, event_date, phone_number)
VALUES (
    1,
    'VOEVODA',
    'The one and only VOEVODA concert. An unforgettable experience awaits you with a display of raw power and musical talent.',
    'Arena Chisinau',
    'Chișinău, str. Calea Orheiului, 130',
    '2025-12-20 19:00:00+02', -- Timezone for Chișinău
    '+37379660101'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    venue_name = EXCLUDED.venue_name,
    venue_address = EXCLUDED.venue_address,
    event_date = EXCLUDED.event_date,
    phone_number = EXCLUDED.phone_number;

-- Clean and insert the performer for our event (event_id = 1).
-- This ensures that even if the script is run again, we don't get duplicate performers.
DELETE FROM performers WHERE event_id = 1;

INSERT INTO performers (event_id, name, image_url)
VALUES (1, 'VOEVODA', '/placeholder-user.jpg'); 